 version: 2
 jobs:
   build:
     docker:
       - image: levity/dapptools-node
     steps:
       - checkout
       - run:
          name: Install dependencies
          command: yarn
       - run:
          name: Run tests
          command: |
            source /home/circleci/setup-env.sh
            yarn lerna bootstrap
            yarn build
            yarn test:build
            yarn coverage
       - run:
          name: codecov
          command: |
            npm i --no-save codecov
            ./node_modules/.bin/codecov
